CREATE TABLE IF NOT EXISTS tasks (
    id INT GENERATED ALWAYS AS IDENTITY,
    task VARCHAR(255) NOT NULL,
    details VARCHAR(500),
    list_id INT NOT NULL
);

CREATE TABLE IF NOT EXISTS lists (
    id INT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    user_id INT NOT NULL
);

ALTER TABLE users ADD COLUMN active_list INT NOT NULL;